config/routes.rb
Blocitoff::Application.routes.draw do
  resources :items

  devise_for :users

  resources :todos, only: [:new, :create, :show]

  resources :lists

  root to: 'home#index'
end

app/models/item.rb
class Item < ActiveRecord::Base
belongs_to :user
belongs_to :list

end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :items, dependent: :destroy
end

app/models/todo.rb
class Todo < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include Pundit
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  def about
  end

  def contact
  end
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @item }
      else
        format.html { render action: 'new' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:list_id, :content, :complete)
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def create
    @list = List.new(params[:list].permit!)

    respond_to do |format|
      if @list.save
        format.html { redirect_to root_path, notice: 'List was successfully created.' }
        format.json { render action: 'show', status: :created, location: @list }
      else
        format.html { render action: 'new' }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @list = List.find(params[:id])
    authorize @list

  end

  def index
    @lists = List.all
   
  end

  private

  def list_params
    params.require(:list).permit(:title)
  end  

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def new
  end

  def create
    @todo = Todo.new(todo_params)
    @todo.save
    redirect_to @todo, notice: 'Your new TODO was saved'
  end

  def show
    @todo = Todo.find params[:id]
  end

  private

  def todo_params
    params.require(:todo).permit(:description)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1> Blocitoff ma fucka </h1>


<!-- going to make form -->


<%= form_for List.new do |f| %>

  Title: <%= f.text_field :title %>

  <%= f.submit %>

<% end %>

<br/>
<div class="jumbotron">

  <p>
      <%= link_to "Sign In", new_user_session_path, class: 'btn btn-primary' %> or 
      <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %> today!
  </p>
</div>

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :list_id %><br>
    <%= f.number_field :list_id %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :complete %><br>
    <%= f.check_box :complete %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Listing items</h1>

<table>
  <thead>
    <tr>
      <th>List</th>
      <th>Content</th>
      <th>Complete</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.list_id %></td>
        <td><%= item.content %></td>
        <td><%= item.complete %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>List:</strong>
  <%= @item.list_id %>
</p>

<p>
  <strong>Content:</strong>
  <%= @item.content %>
</p>

<p>
  <strong>Complete:</strong>
  <%= @item.complete %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocitoff</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
    </head>
    <body>
      <div class="container">

      <ul class="nav nav-tabs">
          <li><%= link_to "Blocitoff", root_path %></li>
          <li><%= link_to "Lists", lists_path %></li>  
          
    


    <div class= "pull-right user-info">
      <% if current_user %>
        Hello <%= current_user.email %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to "Sign In", new_user_session_path %> or
          <%= link_to "Sign Up", new_user_registration_path %>
          <% end %>
        </div>





<p><%= flash[:notice] if flash[:notice] %></p>

<%= yield %>

</body>
</html>

app/views/lists/create.html.erb
Hello world

app/views/lists/index.html.erb
<h1> Lists 6</h1>

<div class="row">
  <div class="col-md-8">
    <% @lists.each do |list| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to list.title, list %>
          </h4>
        </div>
      </div>
      <% end %>
    </div>
  </div>



<div class="col-md-4">
  <% if policy(List.new).create? %>
    <%= link_to "New List", new_list_path, class: 'btn btn-success' %>
    <% end %>
  </div>

app/views/lists/show.html.erb
<h1><%= @list.title %></h1>

<% if policy(@list).update? %>
  <%= link_to "Edit List", edit_list_path, class: 'btn btn-success' %>
<% end %>

  </div>
 <div class="col-md-4">
   <% if policy(Item.new).create? %>
     <%= link_to "New Item", new_item_post_path(@item), class: 'btn btn-success' %>
   <% end %>

   <% if policy(@list).destroy? %>
      <%= link_to "Delete List", @list, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to destroy this lovely list?'} %>
      <% end %>
 </div>
</div>

app/views/todos/new.html.erb
<%= form_for Todo.new do |form| %>
  <%= form.text_field :description, placeholder: 'Description' %>
    <%= form.submit 'Save' %>
<% end %>

app/views/todos/show.html.erb
<p><b><%= @todo.description %></b></p>